In [1]:
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from MultivariatePoisson import MultivariatePoisson as mvp
from scipy.stats import norm, multivariate_normal
from CopulaGenerator import CopulaGenerator
from scipy.optimize import minimize
%load_ext autoreload
%autoreload 2

In [5]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 20))
mp.optimise_params(data, mean, 11.0)

         Current function value: 344.485456
         Iterations: 6
         Function evaluations: 279
         Gradient evaluations: 89
      fun: 344.48545584587686
 hess_inv: array([[0.24480038]])
      jac: array([0.00021744])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 279
      nit: 6
     njev: 89
   status: 2
  success: False
        x: array([1.56380615])


(array([1.56380615]), array([1.75, 1.15]))

In [6]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 50))
x, mu = mp.optimise_params(data, mean, 11.0)
print(x)

      fun: 2333.483152878545
 hess_inv: array([[1.23751257e-08]])
      jac: array([6.10351562e-05])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 462
      nit: 6
     njev: 150
   status: 2
  success: False
        x: array([0.64770011])
[0.64770011]


In [4]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 70))
mp.optimise_params(data, mean, 11.0)

         Current function value: 6554.900647
         Iterations: 6
         Function evaluations: 280
         Gradient evaluations: 90
      fun: 6554.900647050347
 hess_inv: array([[0.08982279]])
      jac: array([0.00079346])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 280
      nit: 6
     njev: 90
   status: 2
  success: False
        x: array([1.99846383])


(array([1.99846383]), array([8.62857143, 9.91428571]))

In [7]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 200))
mp.optimise_params(data, mean, 11.0)

         Current function value: 57378.609605
         Iterations: 7
         Function evaluations: 221
         Gradient evaluations: 70
      fun: 57378.60960546055
 hess_inv: array([[4.82107157e-07]])
      jac: array([-0.28710938])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 221
      nit: 7
     njev: 70
   status: 2
  success: False
        x: array([1.30640701])


(array([1.30640701]), array([ 5.46, 10.72]))

In [8]:
def log_likelihood_archimedean(alpha, data, mean):
    copula = CopulaGenerator(family="clayton", alpha=alpha)
    poiss = mvp("clayton", alpha)
    pm = poiss.pmf(data, mean)
    pm[pm == 0] = 1e-3
    return -sum(np.log10(pm))

In [19]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 1000))

In [17]:
log_likelihood_archimedean(1.0, data, mean)

287.06600413146253