In [1]:
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from MultivariatePoisson import MultivariatePoisson as mvp
from scipy.stats import norm, multivariate_normal
from CopulaGenerator import CopulaGenerator
from scipy.optimize import minimize
%load_ext autoreload
%autoreload 2

In [2]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 20))
mp.optimise_params(data, mean, 11.0)

Optimization terminated successfully.
         Current function value: 583.729047
         Iterations: 8
         Function evaluations: 54
         Gradient evaluations: 18
      fun: 583.7290473146054
 hess_inv: array([[0.2639284]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 54
      nit: 8
     njev: 18
   status: 0
  success: True
        x: array([2.09387633])


(array([2.09387633]), array([ 4.95, 10.3 ]))

In [3]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 50))
mp.optimise_params(data, mean, 11.0)

         Current function value: 2888.679600
         Iterations: 8
         Function evaluations: 64
         Gradient evaluations: 21
      fun: 2888.679600335175
 hess_inv: array([[1.35452865e-07]])
      jac: array([-0.0005188])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 64
      nit: 8
     njev: 21
   status: 2
  success: False
        x: array([2.35301201])


(array([2.35301201]), array([2.32, 4.18]))

In [4]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 70))
mp.optimise_params(data, mean, 11.0)

         Current function value: 6377.325072
         Iterations: 4
         Function evaluations: 142
         Gradient evaluations: 44
      fun: 6377.325071555706
 hess_inv: array([[0.09194756]])
      jac: array([-0.00054932])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 142
      nit: 4
     njev: 44
   status: 2
  success: False
        x: array([5.03902759])


(array([5.03902759]), array([2.04285714, 7.3       ]))

In [7]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 200))
mp.optimise_params(data, mean, 11.0)

         Current function value: 57378.609605
         Iterations: 7
         Function evaluations: 221
         Gradient evaluations: 70
      fun: 57378.60960546055
 hess_inv: array([[4.82107157e-07]])
      jac: array([-0.28710938])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 221
      nit: 7
     njev: 70
   status: 2
  success: False
        x: array([1.30640701])


(array([1.30640701]), array([ 5.46, 10.72]))

In [8]:
def log_likelihood_archimedean(alpha, data, mean):
    copula = CopulaGenerator(family="clayton", alpha=alpha)
    poiss = mvp("clayton", alpha)
    pm = poiss.pmf(data, mean)
    pm[pm == 0] = 1e-3
    return -sum(np.log10(pm))

In [19]:
mp = mvp("clayton", 4.6)
data, mean = mp.rvs(size=(2, 1000))

In [17]:
log_likelihood_archimedean(1.0, data, mean)

287.06600413146253