In [7]:
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
from MultivariatePoisson import MultivariatePoisson as mvp
from scipy.stats import norm, multivariate_normal

In [9]:
multi_poisson = mvp()
multi_poisson.rvs(family="clayton",size=(3,10))

(array([[4., 4., 7., 6., 5., 8., 4., 6., 8., 9.],
        [0., 0., 1., 1., 2., 2., 0., 1., 1., 1.],
        [4., 6., 6., 4., 5., 7., 5., 6., 7., 3.]]),
 array([5.41237437, 0.48339795, 4.79684015]))

In [20]:
multi_poisson.rvs(family="gaussian", size=3)

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 7.,  8.,  9., ...,  3.,  7.,  5.],
        [ 7.,  7., 10., ...,  2.,  6.,  4.]]),
 array([0.39809023, 6.98402317, 5.98228552]))

In [10]:
from CopulaGenerator import CopulaGenerator
cop = CopulaGenerator(2.5, "clayton")

In [41]:
data, mu = multi_poisson.rvs("clayton", size=(2,10))
cop = CopulaGenerator(8.0, "clayton")
alpha, mean = multi_poisson.optimise_params(data, cop)

Optimization terminated successfully.
         Current function value: 121.528323
         Iterations: 69
         Function evaluations: 900


In [42]:
cop = CopulaGenerator(alpha, "clayton")
pmf = multi_poisson.pmf(data, mean, cop)
pmf

array([0.11610573, 0.08719324, 0.02382379, 0.13802584, 0.03318145,
       0.09808272, 0.11610573, 0.0154365 , 0.07615098, 0.04756572])

In [43]:
sum(pmf)

0.7516717004920276

In [54]:
for i in range(20):
    data, mu = multi_poisson.rvs("clayton", size=(3,20))
    cop = CopulaGenerator(8.0, "clayton")
    alpha, mean = multi_poisson.optimise_params(data, cop)
    cop = CopulaGenerator(alpha, "clayton")
    pmf = multi_poisson.pmf(data, mean, cop)
    print(sum(pmf))

nan
nan
Optimization terminated successfully.
         Current function value: 649.640891
         Iterations: 62
         Function evaluations: 807
0.7332806060844257
nan
Optimization terminated successfully.
         Current function value: 696.810013
         Iterations: 69
         Function evaluations: 899
0.6688209356129797
Optimization terminated successfully.
         Current function value: 623.704218
         Iterations: 60
         Function evaluations: 784
0.7703287197745007
Optimization terminated successfully.
         Current function value: 729.123390
         Iterations: 38
         Function evaluations: 497
0.4521253248143074
Optimization terminated successfully.
         Current function value: 716.695990
         Iterations: 69
         Function evaluations: 902
0.5393638084783952
Optimization terminated successfully.
         Current function value: 678.844467
         Iterations: 67
         Function evaluations: 884
0.5825182292077151
Optimization terminated succ

In [23]:
from scipy.optimize import minimize

In [32]:
a = poisson.pmf(data, np.mean(mu[0]))
np.log10(sum(a[0])) + np.log10(sum(a[1]))
def log_likelihood(cop_param, data):
    cop = CopulaGenerator(cop_param[0], "clayton")
    mean = np.array([np.mean(x) for x in data])
    pm = multi_poisson.pmf(data, mean, cop)
    return -sum(np.log10(pm))

minimize(log_likelihood, np.array([18.0]), data, method='powell', options={'disp': True})

Optimization terminated successfully.
         Current function value: 12.813814
         Iterations: 64
         Function evaluations: 835


   direc: array([[1.]])
     fun: 12.813814224475438
 message: 'Optimization terminated successfully.'
    nfev: 835
     nit: 64
  status: 0
 success: True
       x: array(0.69269242)

In [31]:
[np.mean(x) for x in data]

[3.1, 0.9]

In [1]:
a = np.array(([1, 2, 3], [4, 5, 6]))
lamb = np.array([1.6, 2.4])
cop.joint_cdf(a, lamb)

NameError: name 'np' is not defined

In [38]:
a, l = multi_poisson.rvs("clayton", size=(2,10))
b = multi_poisson.pmf(a, l, cop)
b

array([0.14727729, 0.19007851, 0.05285465, 0.05167537, 0.20201612,
       0.23339552, 0.13805546, 0.19755515, 0.19946197, 0.19946197])

In [26]:
cop_ = CopulaGenerator(1.5, "gaussian")
data, mu = multi_poisson.rvs("gaussian", size=(2,10))

[[ 7.  5.  8. ...  4.  4. 10.]
 [ 2.  2.  1. ...  2.  2.  1.]]


In [39]:
b[b == 0.14727729] = 1e-5

In [42]:
g = np.array([1, 2, 3, 0])
g[g == 0] 

array([0])

In [52]:
a = norm.ppf(poisson.cdf(data[0], mu[0]))
b = norm.ppf(poisson.cdf(data[1], mu[1]))
c = []
c.append(a)
c.append(b)
c = np.array(c)
d = np.linspace(0, 5, 10, endpoint=False)
multivariate_normal.cdf(d, mean=None, cov=2.5)

array([0.5       , 0.62408518, 0.73645537, 0.82860914, 0.89704839,
       0.94307685, 0.97111021, 0.98657165, 0.99429398, 0.99778674])

In [54]:
e = np.array([[0.12603256, -0.64046918, 0.48342951, -1.0571831, -1.0571831, 1.15851755], [0.08137796, 0.08137796, -0.5879868, 0.08137796, 0.08137796, -0.5879868]])

In [55]:
multivariate_normal.cdf(e, mean=None, cov=2.5)

error: failed in converting 2nd argument `upper' of mvn.mvnun to C/Fortran array