In [1]:
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%load_ext autoreload
%autoreload 2

In [2]:
from MultivariatePoisson import MultivariatePoisson as mvp
from scipy.stats import norm, multivariate_normal

In [3]:
multi_poisson = mvp()
multi_poisson.rvs(family="gumbel",size=(3,10))

(array([[ 4.,  3.,  5.,  7.,  4.,  1.,  3.,  5.,  1.,  3.],
        [ 7.,  7.,  6., 12.,  7.,  4.,  9.,  7.,  4.,  3.],
        [ 3.,  4.,  1.,  7.,  3.,  3.,  3.,  4.,  2.,  2.]]),
 array([1.97471773, 4.33802832, 2.12370681]))

In [4]:
multi_poisson.rvs(family="gaussian", size=3)

(array([[2., 1., 0., ..., 0., 0., 0.],
        [5., 1., 2., ..., 0., 3., 5.],
        [7., 5., 8., ..., 9., 8., 6.]]),
 array([0.80753725, 3.90563618, 7.50123845]))

In [16]:
from CopulaGenerator import CopulaGenerator
cop = CopulaGenerator(2.5, "clayton")

In [26]:
data, mu = multi_poisson.rvs("clayton", size=(2,10))
data

array([[3., 5., 2., 3., 2., 4., 3., 3., 3., 3.],
       [0., 1., 1., 1., 0., 1., 0., 3., 1., 1.]])

In [23]:
from scipy.optimize import minimize

In [35]:
a = poisson.pmf(data, np.mean(mu[0]))
np.log10(sum(a[0])) + np.log10(sum(a[1]))
def log_likelihood(cop_param, data):
    cop = CopulaGenerator(cop_param[0], "clayton")
    mean = np.array([np.mean(x) for x in data])
    pm = multi_poisson.pmf(data, mean, cop)
    pm[]
    return sum(np.log10(pm))

minimize(log_likelihood, np.array([2.5]), data, method='nelder-mead', options={'disp': True})

/Users/BikoP/miniconda3/envs/HonoursProject/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log10
  import sys


 final_simplex: (array([[98.375],
       [98.375]]), array([-inf, -inf]))
           fun: -inf
       message: 'Maximum number of function evaluations has been exceeded.'
          nfev: 202
           nit: 71
        status: 1
       success: False
             x: array([98.375])

In [31]:
[np.mean(x) for x in data]

[3.1, 0.9]

In [10]:
a = np.array(([1, 2, 3], [4, 5, 6]))
lamb = np.array([1.6, 2.4])
cop.joint_cdf(a, lamb)

array([0.51337955, 0.76774194, 0.91245515])

In [38]:
a, l = multi_poisson.rvs("clayton", size=(2,10))
b = multi_poisson.pmf(a, l, cop)
b

array([0.14727729, 0.19007851, 0.05285465, 0.05167537, 0.20201612,
       0.23339552, 0.13805546, 0.19755515, 0.19946197, 0.19946197])

In [26]:
cop_ = CopulaGenerator(1.5, "gaussian")
data, mu = multi_poisson.rvs("gaussian", size=(2,10))

[[ 7.  5.  8. ...  4.  4. 10.]
 [ 2.  2.  1. ...  2.  2.  1.]]


In [39]:
b[b == 0.14727729] = 1e-5

In [42]:
g = np.array([1, 2, 3, 0])
g[g == 0] 

array([0])

In [52]:
a = norm.ppf(poisson.cdf(data[0], mu[0]))
b = norm.ppf(poisson.cdf(data[1], mu[1]))
c = []
c.append(a)
c.append(b)
c = np.array(c)
d = np.linspace(0, 5, 10, endpoint=False)
multivariate_normal.cdf(d, mean=None, cov=2.5)

array([0.5       , 0.62408518, 0.73645537, 0.82860914, 0.89704839,
       0.94307685, 0.97111021, 0.98657165, 0.99429398, 0.99778674])

In [54]:
e = np.array([[0.12603256, -0.64046918, 0.48342951, -1.0571831, -1.0571831, 1.15851755], [0.08137796, 0.08137796, -0.5879868, 0.08137796, 0.08137796, -0.5879868]])

In [55]:
multivariate_normal.cdf(e, mean=None, cov=2.5)

error: failed in converting 2nd argument `upper' of mvn.mvnun to C/Fortran array