In [1]:
import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%load_ext autoreload
%autoreload 2

In [3]:
from MultivariatePoisson import MultivariatePoisson as mvp
from scipy.stats import norm, multivariate_normal

In [4]:
multi_poisson = mvp()
multi_poisson.rvs(family="gumbel",size=(3,10))

(array([[11.,  7.,  6.,  7.,  8.,  9.,  6., 11.,  7.,  8.],
        [12., 14.,  8., 10., 11., 10., 11., 15.,  9., 10.],
        [10.,  3.,  6.,  6.,  8.,  9.,  3., 10.,  7.,  7.]]),
 array([6.50996919, 9.20413491, 5.94514176]))

In [5]:
multi_poisson.rvs(family="gaussian", size=3)

(array([[14.,  0.,  1., ...,  7.,  5., 12.],
        [ 9.,  2.,  4., ...,  9.,  5., 11.],
        [10.,  5.,  5., ...,  7.,  6.,  8.]]),
 array([4.66210916, 6.76564464, 7.22372109]))

In [6]:
from CopulaGenerator import CopulaGenerator
cop = CopulaGenerator(2.5, "clayton")

In [7]:
data, mu = multi_poisson.rvs("clayton", size=(2,10))
data

array([[ 1.,  0.,  1.,  1.,  2.,  1.,  0.,  2.,  0.,  0.],
       [ 5.,  4.,  5.,  4.,  4.,  5.,  2., 10.,  3.,  7.]])

In [12]:
from scipy.optimize import maximize

ImportError: cannot import name 'maximize' from 'scipy.optimize' (/Users/BikoP/miniconda3/envs/HonoursProject/lib/python3.7/site-packages/scipy/optimize/__init__.py)

In [16]:
a = poisson.pmf(data, np.mean(mu[0]))
np.log10(sum(a[0])) + np.log10(sum(a[1]))
def log_likelihood(cop_param, data):
    cop = CopulaGenerator(cop_param[0], "clayton")
    mean = np.array([np.mean(x) for x in data])
    pm = multi_poisson.pmf(data, mean, cop)
    print("iteration: " + str(pm))
    return -sum(np.log10(pm))

minimize(log_likelihood, np.array([2.5]), data, method='powell', options={'disp': True})

iteration: [0.14322776 0.09946444 0.14322776 0.16497439 0.17613841 0.14322776
 0.08729188 0.01392405 0.12321447 0.01067438]
iteration: [0.14322776 0.09946444 0.14322776 0.16497439 0.17613841 0.14322776
 0.08729188 0.01392405 0.12321447 0.01067438]
iteration: [0.14887191 0.10900136 0.14887191 0.17088989 0.17746902 0.14887191
 0.08889479 0.01334261 0.13374916 0.00606578]
iteration: [0.13750972 0.08441677 0.13750972 0.15024812 0.1721367  0.13750972
 0.07032476 0.01496711 0.090453   0.02647336]
iteration: [0.13864282 0.08971402 0.13864282 0.15634373 0.17390582 0.13864282
 0.08085167 0.01455126 0.10542917 0.01864798]
iteration: [0.13864282 0.08971402 0.13864282 0.15634373 0.17390582 0.13864282
 0.08085167 0.01455126 0.10542917 0.01864798]
iteration: [0.14013754 0.09336745 0.14013754 0.15992841 0.17487258 0.14013754
 0.08434693 0.01430579 0.11319086 0.01507012]
iteration: [0.13797459 0.08756354 0.13797459 0.15400927 0.17324681 0.13797459
 0.07767218 0.0147076  0.10002274 0.02129887]
iteratio

   direc: array([[1.]])
     fun: 10.822870419313968
 message: 'Optimization terminated successfully.'
    nfev: 22
     nit: 2
  status: 0
 success: True
       x: array(1.49993801)

In [31]:
[np.mean(x) for x in data]

[3.1, 0.9]

In [10]:
a = np.array(([1, 2, 3], [4, 5, 6]))
lamb = np.array([1.6, 2.4])
cop.joint_cdf(a, lamb)

array([0.51337955, 0.76774194, 0.91245515])

In [38]:
a, l = multi_poisson.rvs("clayton", size=(2,10))
b = multi_poisson.pmf(a, l, cop)
b

array([0.14727729, 0.19007851, 0.05285465, 0.05167537, 0.20201612,
       0.23339552, 0.13805546, 0.19755515, 0.19946197, 0.19946197])

In [26]:
cop_ = CopulaGenerator(1.5, "gaussian")
data, mu = multi_poisson.rvs("gaussian", size=(2,10))

[[ 7.  5.  8. ...  4.  4. 10.]
 [ 2.  2.  1. ...  2.  2.  1.]]


In [39]:
b[b == 0.14727729] = 1e-5

In [42]:
g = np.array([1, 2, 3, 0])
g[g == 0] 

array([0])

In [52]:
a = norm.ppf(poisson.cdf(data[0], mu[0]))
b = norm.ppf(poisson.cdf(data[1], mu[1]))
c = []
c.append(a)
c.append(b)
c = np.array(c)
d = np.linspace(0, 5, 10, endpoint=False)
multivariate_normal.cdf(d, mean=None, cov=2.5)

array([0.5       , 0.62408518, 0.73645537, 0.82860914, 0.89704839,
       0.94307685, 0.97111021, 0.98657165, 0.99429398, 0.99778674])

In [54]:
e = np.array([[0.12603256, -0.64046918, 0.48342951, -1.0571831, -1.0571831, 1.15851755], [0.08137796, 0.08137796, -0.5879868, 0.08137796, 0.08137796, -0.5879868]])

In [55]:
multivariate_normal.cdf(e, mean=None, cov=2.5)

error: failed in converting 2nd argument `upper' of mvn.mvnun to C/Fortran array